"""畫面區塊座標常數。列（row）與欄（col）皆從 0 開始，scene 不得直接寫死座標數字。"""

SCREEN_WIDTH = 96
SCREEN_HEIGHT = 32

# --- 主框（列 0 到 20） ---
FRAME_LEFT = 0
FRAME_RIGHT = 95
FRAME_TOP = 0
FRAME_BOTTOM = 20
FRAME_WIDTH = FRAME_RIGHT - FRAME_LEFT + 1
FRAME_HEIGHT = FRAME_BOTTOM - FRAME_TOP + 1

PANEL_DIVIDER_COL = 63
LEFT_CONTENT_START = 1
LEFT_CONTENT_END = 62
RIGHT_CONTENT_START = 64
RIGHT_CONTENT_END = 94

HEADER_ROW = 1  # 樓層／回合數（左）、面板標題（右）
LEFT_DIVIDER_ROW = 2  # 只在左面板畫分隔線

ENEMY_ART_TOP = 3
ENEMY_ART_BOTTOM = 12
ENEMY_ART_WIDTH = 24
ENEMY_ART_HEIGHT = ENEMY_ART_BOTTOM - ENEMY_ART_TOP + 1  # 10

ENEMY_BANNER_ROW = 13  # ════[ 名稱 ]════
ENEMY_HP_ROW = 14
ENEMY_INTENT_ROW = 15
ENEMY_STATUS_ROW = 16  # 第一階段留空

FULL_DIVIDER_ROW = 17  # 欄 0 ╠、欄 63 ╩、欄 95 ╣

PLAYER_STATUS_ROW = 18
PLAYER_STATUS2_ROW = 19  # 第一階段留空

# --- 右面板（列 3 到 16，寬 31） ---
RIGHT_PANEL_TOP = ENEMY_ART_TOP
RIGHT_PANEL_BOTTOM = ENEMY_STATUS_ROW
RIGHT_PANEL_WIDTH = RIGHT_CONTENT_END - RIGHT_CONTENT_START + 1 + 2  # 含左右邊框共 31
RIGHT_PANEL_CONTENT_WIDTH = 29

# --- 手牌（列 21 到 30） ---
HAND_ROW_TOP = 21
HAND_ROW_BOTTOM = 30
CARD_WIDTH = 12
CARD_HEIGHT = 10
CARD_MAX_COUNT = 7
CARD_SLOT_START_COL = 3
CARD_SLOT_STRIDE = 13  # CARD_WIDTH + 1 格間距


def card_slot_x(index: int) -> int:
    """第 index 張手牌（從 0 開始）左上角的欄座標。"""
    return CARD_SLOT_START_COL + index * CARD_SLOT_STRIDE


# --- 操作提示（列 31） ---
HINT_ROW = 31
